{% set version = "2.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fpp2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fpp2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fpp2/fpp2_{{ version }}.tar.gz
  sha256: 0ed8d9a2716fb2dcaa0da68637a0311dd0ae8a9f6e648bcf2ca5e0908f9384d6

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-expsmooth
    - r-fma
    - r-forecast >=8.3
    - r-ggplot2
    - r-magrittr >=1.5
    - r-purrr >=0.2.4
    - r-rstudioapi >=0.7
  run:
    - r-base
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-expsmooth
    - r-fma
    - r-forecast >=8.3
    - r-ggplot2
    - r-magrittr >=1.5
    - r-purrr >=0.2.4
    - r-rstudioapi >=0.7

test:
  commands:
    - $R -e "library('fpp2')"           # [not win]
    - "\"%R%\" -e \"library('fpp2')\""  # [win]

about:
  home: https://pkg.robjhyndman.com/fpp2-package, https://github.com/robjhyndman/fpp2-package, https://OTexts.org/fpp2/
  license: GPL-3.0-only
  summary: 'All data sets required for the examples and exercises  in the book "Forecasting: principles and practice"  by Rob J Hyndman and George Athanasopoulos <https://OTexts.org/fpp2/>.  All packages required to run the examples are also loaded.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: fpp2
# Version: 2.3
# Title: Data for "Forecasting: Principles and Practice" (2nd Edition)
# Description: All data sets required for the examples and exercises  in the book "Forecasting: principles and practice"  by Rob J Hyndman and George Athanasopoulos <https://OTexts.org/fpp2/>.  All packages required to run the examples are also loaded.
# Depends: R (>= 2.10), ggplot2, forecast (>= 8.3), fma, expsmooth
# Suggests: GGally,gridExtra,Mcomp,purrr,seasonal,tidyverse,vars
# LazyData: yes
# LazyLoad: yes
# Authors@R: c(person(given="Rob", family="Hyndman", role=c("aut", "cre", "cph"), email="Rob.Hyndman@monash.edu"))
# License: GPL (>= 3)
# RoxygenNote: 6.0.1
# URL: https://pkg.robjhyndman.com/fpp2-package, https://github.com/robjhyndman/fpp2-package, https://OTexts.org/fpp2/
# NeedsCompilation: no
# Packaged: 2018-04-13 02:15:43 UTC; hyndman
# Author: Rob Hyndman [aut, cre, cph]
# Maintainer: Rob Hyndman <Rob.Hyndman@monash.edu>
# Repository: CRAN
# Date/Publication: 2018-04-13 05:30:35 UTC
